Added eraPoints, commission, controllerId, NextSessionIds
hicommonwealth/chain-events pull request #28
Opened 2020-09-15 00:03 UTC by nblogist

Conversation at https://github.com/hicommonwealth/chain-events/issues/27
I have added Erapoints, Commission, controllerId, NextSessionKeys in the new Session Event

2020-09-15 14:09 UTC, jnaviask commented
Tests failing?

Also, this is a lot of overhead for every event. Do we want to be doing this? @drewstone

2020-09-18 01:00 UTC, drewstone commented
@zohaib01khan are you taking this PR over? I think this is fine @jnaviask, these queries are only being run each hour.

2020-09-18 01:01 UTC, drewstone commented
We can likely optimise all this querying though, but I would like to know what eventHandlers these larger querys like validatorInfo are going to be used for, maybe @nblogist @zohaib01khan can shed some light on the intention

2020-09-18 01:09 UTC, drewstone requested changes

2020-09-18 01:09 UTC, drewstone commented on src/substrate/types.ts
> +  validatorInfo : {},
add type

2020-09-18 01:14 UTC, zohaib01khan commented
> @zohaib01khan are you taking this PR over? I think this is fine @jnaviask, these queries are only being run each hour.

@drew new-session and rewards event handlers will be utilizing this information.
https://github.com/hicommonwealth/commonwealth/pull/782/files/efacb45e9cd3e0d0b0467ce48b4ea0eff4137a79#diff-984a722de7058e672a30357c64ffcf5eR89-R90

https://github.com/hicommonwealth/commonwealth/pull/782/files/efacb45e9cd3e0d0b0467ce48b4ea0eff4137a79#diff-0f1fe4ace565ee63a6626bdd411d58ccR62

2020-10-13 12:41 UTC, nblogist commented on src/substrate/types.ts
> +  validatorInfo : {},
Done

2020-10-28 11:26 UTC, nblogist commented
@drewstone  Any updates on this?

2020-11-03 18:05 UTC, drewstone commented
Why is the build failing with `unwrap is not a function` @nblogist ?

2020-11-06 14:13 UTC, nblogist commented
@drewstone I tried without unwrap, unwrap was being called on an intermediate value (in a Promise), causing code to break.
@jnaviask  Tests are passing now.

Please let me know if there's anything else.

2020-11-09 15:54 UTC, merged